### ISSUE TITLE
Về việc render static page

### ISSUE THREAD

**Issue by tienhieuD** [nguyendangbanghn93/crud-next-js#1]
Đoạn này chắc anh nhầm chút về việc render static page.
Nếu viết thế này thì danh sách students sẽ render on build.
Tức là khi ở production, thêm mới 1 student thì sẽ phải build lại 1 lần nữa mới thấy trang chi tiết.

![image](https://user-images.githubusercontent.com/16768170/127638470-dcd2f383-55ad-4000-b4a3-1ed5619d8c4a.png)

**Comment by nguyendangbanghn93** [comment]
Ở getStaticPaths trong return anh cho "fallback = true". 
Có nghĩa là anh vẫn tải trước những thằng student có sẵn. Còn những thằng student tạo ra sau đó thì khi vào nó vẫn sẽ đợi để đi tải thằng student mới.
Nếu "fallback = false" Thì khi vào những thằng student được tạo ra sau nó sẽ trả về trang 404 notfound.

**Comment by nguyendangbanghn93** [comment]
> Đoạn này chắc anh nhầm chút về việc render static page.
> Nếu viết thế này thì danh sách students sẽ render on build.
> Tức là khi ở production, thêm mới 1 student thì sẽ phải build lại 1 lần nữa mới thấy trang chi tiết.
> 
> ![image](https://user-images.githubusercontent.com/16768170/127638470-dcd2f383-55ad-4000-b4a3-1ed5619d8c4a.png)
